name: studymate
description: Studymate app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0 # Untuk font Inter dan Montserrat
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  
  fonts:
    - family: MontserratAlternates
      fonts:
        - asset: assets/fonts/MontserratAlternates-SemiBold.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-SemiBold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf