// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxhlwxM5C4rQzKO19kqAwgL4-Gd3DdJ_k',
    appId: '1:861714301924:web:7ed4426823966c1215bdf1',
    messagingSenderId: '861714301924',
    projectId: 'studymate-8e8ec',
    authDomain: 'studymate-8e8ec.firebaseapp.com',
    storageBucket: 'studymate-8e8ec.firebasestorage.app',
    measurementId: 'G-ZJXHTKJ1KJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi4myudLfIVfV3_0_EuLeFrLM45If1uHE',
    appId: '1:861714301924:android:7b1234e27fe2f28b15bdf1',
    messagingSenderId: '861714301924',
    projectId: 'studymate-8e8ec',
    storageBucket: 'studymate-8e8ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtvAKtWLOrsKq93jbdynjgI4cZl8OB6DI',
    appId: '1:528368875856:ios:a8d7650f196f199b3b9455',
    messagingSenderId: '528368875856',
    projectId: 'study-mate-eef32',
    storageBucket: 'study-mate-eef32.firebasestorage.app',
    iosBundleId: 'com.example.studyMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtvAKtWLOrsKq93jbdynjgI4cZl8OB6DI',
    appId: '1:528368875856:ios:a8d7650f196f199b3b9455',
    messagingSenderId: '528368875856',
    projectId: 'study-mate-eef32',
    storageBucket: 'study-mate-eef32.firebasestorage.app',
    iosBundleId: 'com.example.studyMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxhlwxM5C4rQzKO19kqAwgL4-Gd3DdJ_k',
    appId: '1:861714301924:web:3929870812fa5c7115bdf1',
    messagingSenderId: '861714301924',
    projectId: 'studymate-8e8ec',
    authDomain: 'studymate-8e8ec.firebaseapp.com',
    storageBucket: 'studymate-8e8ec.firebasestorage.app',
    measurementId: 'G-ND8CL7T28Y',
  );

}