// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP1VsOn8xb_CLNVFCL2Gp13zTGkJ-WKIo',
    appId: '1:528368875856:web:7e3c8452ca9318913b9455',
    messagingSenderId: '528368875856',
    projectId: 'study-mate-eef32',
    authDomain: 'study-mate-eef32.firebaseapp.com',
    storageBucket: 'study-mate-eef32.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq4bMLZt6hCN8IJAQJ9j6lT0Bg8YLO1kA',
    appId: '1:528368875856:android:f6ac3fe03d1d5da43b9455',
    messagingSenderId: '528368875856',
    projectId: 'study-mate-eef32',
    storageBucket: 'study-mate-eef32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtvAKtWLOrsKq93jbdynjgI4cZl8OB6DI',
    appId: '1:528368875856:ios:a8d7650f196f199b3b9455',
    messagingSenderId: '528368875856',
    projectId: 'study-mate-eef32',
    storageBucket: 'study-mate-eef32.firebasestorage.app',
    iosBundleId: 'com.example.studyMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtvAKtWLOrsKq93jbdynjgI4cZl8OB6DI',
    appId: '1:528368875856:ios:a8d7650f196f199b3b9455',
    messagingSenderId: '528368875856',
    projectId: 'study-mate-eef32',
    storageBucket: 'study-mate-eef32.firebasestorage.app',
    iosBundleId: 'com.example.studyMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP1VsOn8xb_CLNVFCL2Gp13zTGkJ-WKIo',
    appId: '1:528368875856:web:b74e94c6ea8524953b9455',
    messagingSenderId: '528368875856',
    projectId: 'study-mate-eef32',
    authDomain: 'study-mate-eef32.firebaseapp.com',
    storageBucket: 'study-mate-eef32.firebasestorage.app',
  );
}
